//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepDX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StepDX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bulletbill {
            get {
                object obj = ResourceManager.GetObject("bulletbill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cloud {
            get {
                object obj = ResourceManager.GetObject("cloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream die {
            get {
                return ResourceManager.GetStream("die", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap finishlineplatform {
            get {
                object obj = ResourceManager.GetObject("finishlineplatform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;!--Mario App Scoreboard Persistent Storage--&gt;
        ///&lt;scoreboard&gt;
        ///  &lt;score name=&quot;Alec&quot; value=&quot;671&quot; /&gt;
        ///  &lt;score name=&quot;Aaron&quot; value=&quot;180&quot; /&gt;
        ///  &lt;score name=&quot;Aaron&quot; value=&quot;708&quot; /&gt;
        ///  &lt;score name=&quot;Aaron&quot; value=&quot;481&quot; /&gt;
        ///  &lt;score name=&quot;Aaron&quot; value=&quot;735&quot; /&gt;
        ///&lt;/scoreboard&gt;.
        /// </summary>
        internal static string highscores {
            get {
                return ResourceManager.GetString("highscores", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream jump {
            get {
                return ResourceManager.GetStream("jump", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream kick {
            get {
                return ResourceManager.GetStream("kick", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mario8 {
            get {
                object obj = ResourceManager.GetObject("mario8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream mariodie {
            get {
                return ResourceManager.GetStream("mariodie", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream stage_clear {
            get {
                return ResourceManager.GetStream("stage_clear", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap stone08 {
            get {
                object obj = ResourceManager.GetObject("stone08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap texture1 {
            get {
                object obj = ResourceManager.GetObject("texture1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap texture2 {
            get {
                object obj = ResourceManager.GetObject("texture2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap texture3 {
            get {
                object obj = ResourceManager.GetObject("texture3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap texture4 {
            get {
                object obj = ResourceManager.GetObject("texture4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap texture5 {
            get {
                object obj = ResourceManager.GetObject("texture5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap texture6 {
            get {
                object obj = ResourceManager.GetObject("texture6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
